{
 "title": "My_VM_CPU_DASH",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Apache_logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{container=\"apache\"} |= ``"
    }
   ]
  },
  {
   "title": "Nginx_logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{container=\"nginx\"} |= ``"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "100 * (1 - (irate(node_cpu_seconds_total{cpu=\"0\", mode=\"idle\", metric=\"cpu\"}[9s])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "(100 * ((node_memory_MemTotal_bytes{metric=\"memory\"} - node_memory_MemFree_bytes{metric=\"memory\"} - node_memory_Buffers_bytes{metric=\"memory\"} - node_memory_Cached_bytes{metric=\"memory\"} - node_memory_SReclaimable_bytes{metric=\"memory\"}) / node_memory_MemTotal_bytes{metric=\"memory\"}))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}