apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv-volume
  namespace: monitoring
  labels:
    type: local
    purpose: grafana
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/working/grafana-volume/grafana"