apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mystorage
  volumeMode: Filesystem  # Добавлено обязательное поле volumeMode


persistence:
  enabled: true
  type: pvc
  storageClassName: default
  accessModes:
  - ReadWriteOnce
  size: 4Gi
  finalizers:
  - kubernetes.io/pvc-protection
