FROM nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY ../task5/index.html /usr/share/nginx/html/index.html
#RUN mkdir /var/www/html/music/ && touch /var/www/html/music/ms.mp3


# docker build -t nginx-docker .
# docker run -d -p 80:80 nginx-docker