FROM php:7.4-apache

# Add custom PHP script
RUN echo "<?php phpinfo(); ?>" > /var/www/html/index.php

# Copy custom Apache configuration
#COPY 000-default.conf /etc/apache2/sites-available/000-default.conf
#
# COPY ports.conf /etc/apache2/ports.conf

# Change default Apache start page
# COPY custom-index.html /var/www/html/index.html

