global:
  resolve_timeout: 1m

route:
  group_by:
    - aproject
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'slack'


receivers:
  - name: 'slack'

    slack_configs:
      - api_url: #some url
        channel: #a-project
        send_resolved: false
        text: "{{ .CommonAnnotations.description }}"

