apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: vote
spec:
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
  selector:
    name: redis-deployment
