apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: danwhite123/nginx-image
        volumeMounts:
          - name: default-conf
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
          - name: default-page
            mountPath: /usr/share/nginx/html

      volumes:
        - name: default-conf
          configMap:
            name: default-conf
        - name: default-page
          configMap:
            name: default-page

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
