groups:
  - name: example
    rules:
      - alert: HighCpuUsage
        expr: 100 - (avg(irate(node_cpu_seconds_total{mode="idle"}[10s])) * 100)
        for: 10s
        labels:
          severity: warning
        annotations:
          description: The average CPU load is {{ humanize $value }}% on instance {{ $labels.instance }}
          summary: High CPU Load
