groups:
  - name: example
    rules:
      - alert: HighCpuUsage
        expr: 100 - (avg(irate(node_cpu_seconds_total{mode="idle"}[1m])) * 100)
        for: 1m
        labels:
          severity: warning
        annotations:
          description: The average CPU load is {{ humanize $value }}% on instance {{ $labels.instance }}
          summary: High CPU Load
