groups:
  - name: example
    rules:
      - alert: HighCpuUsage
        expr: 100 * (1 - (irate(node_cpu_seconds_total{mode="idle", job="node-exporter-some"}[1m]))) < 80
        for: 10s
        labels:
          severity: warning
        annotations:
          description: The average CPU load is {{ humanize $value }}% on instance {{ $labels.instance }}
          summary: High CPU Load
