global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 1m

alerting:
  alertmanagers:
    - follow_redirects: true
      enable_http2: true
      scheme: http
      timeout: 10s
      api_version: v2
      static_configs:
        - targets:
          - alertmanager:9093

rule_files:
  - /etc/prometheus/alert-rules.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - prometheus:9090

  - job_name: 'node-exporter-some'
    static_configs:
      - targets: [ 'node-exporter:9100' ]



