---
- name: Install Docker and run container
  hosts:
    - ubuntu_group
    - amazon_group
  become: true

  tasks:
    - block:
      - name: Install prerequisites for Docker on Ubuntu
        apt:
          pkg:
            - apt-transport-https
            - ca-certificates
            - curl
            - software-properties-common
            - python3-pip
            - virtualenv
            - python3-setuptools
          state: latest
          update_cache: true

      - name: Add Docker GPG key Ubuntu
        apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
          state: present

      - name: Add Docker APT repository Ubuntu
        apt_repository:
          repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
          state: present

      - name: Install Docker on Ubuntu
        apt:
          name:
            - docker-ce
            - docker-compose
          state: latest
          update_cache: true
      when: ansible_os_family == "Debian"

    - block:
      - name: Add Docker GPG key Amazon
        rpm_key:
          key: "https://download.docker.com/linux/rhel/gpg"
          state: present

      - name: Add Docker YUM repository Amazon
        yum_repository:
          name: docker
          description: docker repository
          baseurl: "https://download.docker.com/linux/rhel/$releasever/$basearch/stable"
          gpgcheck: true
          gpgkey: "https://download.docker.com/linux/rhel/gpg"
          state: present

      - name: Install Docker on Amazon
        dnf:
          name:
            - docker
            - git
          state: latest
          update_cache: true

      - name: Remove python3-requests
        dnf:
          name: python3-requests
          state: absent

      - name: Ensure pip is installed
        ansible.builtin.dnf:
          name: python3-pip
          state: present

      - name: Install Docker Module for Python
        pip:
          name: docker
      when: ansible_os_family == "RedHat"

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Clone the Git repository
      git:
        repo: https://github.com/Nerogen/ansible_setup.git
        dest: ./dg/
        version: master  # Specify the branch or tag you want to clone (optional)

    - name: Run docker-compose up
      ansible.builtin.shell:
        cmd: cd dg/ && docker-compose up -d
